export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            padding: "1rem",
            backgroundColor: "ghostWhite",
          }}
        >
          <p>Header</p>
        </div>
        {children}
        <div
          style={{
            padding: "1rem",
            backgroundColor: "grey",
          }}
        >
          <p>Header</p>
        </div>
      </body>
    </html>
  );
}
